// 여행핀 큐레이션 데이터 — 국내/해외 24곳, 풍부한 여행 콘텐츠
export type Region = "국내" | "아시아" | "유럽" | "미주" | "오세아니아";

export interface Destination {
  id: string;
  name: string;
  country: string;
  flag: string;
  region: Region;
  tagline: string;
  // 3D 지구본 좌표
  lat: number;
  lng: number;
  // 카드 그라데이션
  c1: string;
  c2: string;
  bestSeason: string;
  budgetPerDay: string; // 1일 예상 경비
  flightTime: string; // ICN 기준
  vibe: string[];
  mustSee: { title: string; desc: string }[];
  tips: string[];
  // 맥락 제휴(여행용품) 키워드
  gear: string[];
}

export const DESTINATIONS: Destination[] = [
  {
    id: "jeju",
    name: "제주",
    country: "대한민국",
    flag: "🇰🇷",
    region: "국내",
    tagline: "오름과 바다, 가장 가까운 이국",
    lat: 33.49, lng: 126.53, c1: "#0ea5e9", c2: "#22c55e",
    bestSeason: "4~6월 · 9~10월 (유채·억새)",
    budgetPerDay: "₩90,000~150,000",
    flightTime: "약 1시간",
    vibe: ["바다", "드라이브", "카페", "올레길"],
    mustSee: [
      { title: "성산일출봉", desc: "유네스코 세계자연유산. 새벽 일출 명소." },
      { title: "한라산 영실코스", desc: "초보도 가능한 5시간 왕복, 봄철 진달래." },
      { title: "협재·금능 해변", desc: "에메랄드빛 수심, 비양도 배경." },
    ],
    tips: ["렌터카 필수 — 성수기 미리 예약", "동/서부 하루씩 나눠 동선 짜기", "흑돼지·고기국수·해녀물질 체험"],
    gear: ["여행용 캐리어", "방수 샌들", "보조배터리"],
  },
  {
    id: "busan",
    name: "부산",
    country: "대한민국",
    flag: "🇰🇷",
    region: "국내",
    tagline: "산복도로와 바다열차의 도시",
    lat: 35.18, lng: 129.08, c1: "#f97316", c2: "#06b6d4",
    bestSeason: "5월 · 10월 (불꽃축제)",
    budgetPerDay: "₩70,000~120,000",
    flightTime: "KTX 약 2시간 40분",
    vibe: ["야경", "회", "해변", "감성"],
    mustSee: [
      { title: "해운대 블루라인파크", desc: "해변열차+스카이캡슐, 동해 절경." },
      { title: "감천문화마을", desc: "산토리니 닮은 컬러풀 골목." },
      { title: "광안리 더비치", desc: "야간 광안대교 라이트쇼." },
    ],
    tips: ["자갈치·기장 회 가성비", "지하철+버스 패스 활용", "해돋이는 해운대, 야경은 황령산"],
    gear: ["운동화", "선크림", "에코백"],
  },
  {
    id: "gangneung",
    name: "강릉",
    country: "대한민국",
    flag: "🇰🇷",
    region: "국내",
    tagline: "커피향과 동해 일출",
    lat: 37.75, lng: 128.87, c1: "#0891b2", c2: "#7c3aed",
    bestSeason: "여름 해변 · 겨울 일출",
    budgetPerDay: "₩60,000~110,000",
    flightTime: "KTX 약 2시간",
    vibe: ["커피", "해변", "드라이브"],
    mustSee: [
      { title: "안목 커피거리", desc: "바다 보며 마시는 강릉 커피의 성지." },
      { title: "정동진 일출", desc: "기차로 닿는 가장 유명한 해돋이." },
      { title: "오죽헌·경포호", desc: "솔향수목원 산책 코스." },
    ],
    tips: ["주말 차량 정체 — 이른 출발", "초당순두부 아침", "겨울 별빛 일출 명소"],
    gear: ["텀블러", "패딩", "휴대용 의자"],
  },
  {
    id: "tokyo",
    name: "도쿄",
    country: "일본",
    flag: "🇯🇵",
    region: "아시아",
    tagline: "전통과 미래가 겹쳐진 메가시티",
    lat: 35.68, lng: 139.69, c1: "#ef4444", c2: "#8b5cf6",
    bestSeason: "3월말 벚꽃 · 11월 단풍",
    budgetPerDay: "¥12,000~20,000",
    flightTime: "약 2시간 20분",
    vibe: ["미식", "쇼핑", "애니", "야경"],
    mustSee: [
      { title: "센소지·아사쿠사", desc: "도쿄에서 가장 오래된 절, 나카미세 거리." },
      { title: "시부야 스크램블", desc: "세계에서 가장 붐비는 교차로." },
      { title: "팀랩 플래닛", desc: "몰입형 디지털 아트 뮤지엄." },
    ],
    tips: ["스이카/파스모 교통카드", "라멘·스시 오마카세 예약", "긴자·하라주쿠 쇼핑 분리"],
    gear: ["편한 운동화", "포켓 와이파이", "접이식 우산"],
  },
  {
    id: "osaka",
    name: "오사카",
    country: "일본",
    flag: "🇯🇵",
    region: "아시아",
    tagline: "먹고 쓰러지는 도시, 천하의 부엌",
    lat: 34.69, lng: 135.50, c1: "#f59e0b", c2: "#ec4899",
    bestSeason: "봄·가을",
    budgetPerDay: "¥10,000~17,000",
    flightTime: "약 1시간 50분",
    vibe: ["미식", "테마파크", "야시장"],
    mustSee: [
      { title: "도톤보리", desc: "글리코 간판과 길거리 음식의 천국." },
      { title: "유니버설 스튜디오", desc: "닌텐도 월드, 해리포터." },
      { title: "오사카성", desc: "벚꽃 시즌 최고의 포토존." },
    ],
    tips: ["타코야키·오코노미야키 필수", "교토·나라 당일치기 거점", "간사이 스루패스"],
    gear: ["크로스백", "보조배터리", "위장약"],
  },
  {
    id: "danang",
    name: "다낭",
    country: "베트남",
    flag: "🇻🇳",
    region: "아시아",
    tagline: "바다·골프·마사지, 가성비 휴양",
    lat: 16.05, lng: 108.21, c1: "#14b8a6", c2: "#f43f5e",
    bestSeason: "2~5월 (건기)",
    budgetPerDay: "$40~80",
    flightTime: "약 4시간 30분",
    vibe: ["휴양", "마사지", "해산물", "골프"],
    mustSee: [
      { title: "바나힐 골든브릿지", desc: "거대한 손이 받친 황금다리." },
      { title: "미케비치", desc: "10km 백사장, 일출 산책." },
      { title: "호이안 올드타운", desc: "밤이면 등불 켜지는 세계유산." },
    ],
    tips: ["그랩 택시 필수", "달러·동 환전 소액 분산", "스파 사전 예약 할인"],
    gear: ["래쉬가드", "방수 파우치", "모기 기피제"],
  },
  {
    id: "bangkok",
    name: "방콕",
    country: "태국",
    flag: "🇹🇭",
    region: "아시아",
    tagline: "사원과 루프탑, 24시간 미식도시",
    lat: 13.75, lng: 100.50, c1: "#eab308", c2: "#a855f7",
    bestSeason: "11~2월 (선선)",
    budgetPerDay: "$35~70",
    flightTime: "약 6시간",
    vibe: ["사원", "야시장", "루프탑바", "마사지"],
    mustSee: [
      { title: "왓포·왓아룬", desc: "와불상과 새벽사원." },
      { title: "짜뚜짝 주말시장", desc: "1만 5천 점포의 미로." },
      { title: "차오프라야 디너크루즈", desc: "강 위에서 보는 야경." },
    ],
    tips: ["BTS·MRT로 교통체증 회피", "길거리 음식 천국", "왕궁 복장 규정 주의"],
    gear: ["얇은 긴팔(사원)", "선글라스", "지사제"],
  },
  {
    id: "taipei",
    name: "타이베이",
    country: "대만",
    flag: "🇹🇼",
    region: "아시아",
    tagline: "야시장과 온천, 3시간의 작은 여행",
    lat: 25.03, lng: 121.56, c1: "#22d3ee", c2: "#fb7185",
    bestSeason: "10~4월",
    budgetPerDay: "$40~75",
    flightTime: "약 2시간 40분",
    vibe: ["야시장", "온천", "딤섬"],
    mustSee: [
      { title: "스펀 천등날리기", desc: "소원 적은 등불을 하늘로." },
      { title: "지우펀", desc: "센과 치히로 감성 산골 마을." },
      { title: "딘타이펑 본점", desc: "샤오롱바오의 원조." },
    ],
    tips: ["이지카드 충전", "버블티·망고빙수", "베이터우 온천 당일치기"],
    gear: ["우산", "편한 신발", "에코백"],
  },
  {
    id: "bali",
    name: "발리",
    country: "인도네시아",
    flag: "🇮🇩",
    region: "아시아",
    tagline: "신들의 섬, 서핑과 요가의 낙원",
    lat: -8.34, lng: 115.09, c1: "#10b981", c2: "#f97316",
    bestSeason: "4~10월 (건기)",
    budgetPerDay: "$45~90",
    flightTime: "약 7시간",
    vibe: ["서핑", "요가", "풀빌라", "선셋"],
    mustSee: [
      { title: "우붓 라이스테라스", desc: "계단식 논의 초록 물결." },
      { title: "울루와뚜 절벽사원", desc: "케착댄스와 선셋." },
      { title: "누사페니다", desc: "켈링킹 비치 절경." },
    ],
    tips: ["풀빌라 가성비 최고", "스쿠터 대신 그랩", "사원 사롱 착용"],
    gear: ["서프 래쉬가드", "방수카메라", "선크림"],
  },
  {
    id: "paris",
    name: "파리",
    country: "프랑스",
    flag: "🇫🇷",
    region: "유럽",
    tagline: "예술과 미식, 영원한 로망",
    lat: 48.86, lng: 2.35, c1: "#6366f1", c2: "#f472b6",
    bestSeason: "4~6월 · 9~10월",
    budgetPerDay: "€120~200",
    flightTime: "약 14시간",
    vibe: ["미술관", "건축", "베이커리", "야경"],
    mustSee: [
      { title: "루브르 박물관", desc: "모나리자, 미리 온라인 예약." },
      { title: "에펠탑 야경", desc: "정시 5분 반짝임 쇼." },
      { title: "몽마르트·사크레쾨르", desc: "언덕 위 화가의 거리." },
    ],
    tips: ["뮤지엄 패스로 줄서기 절약", "소매치기 주의", "크루아상은 동네 불랑제리"],
    gear: ["편한 워킹화", "크로스백(앞으로)", "유럽 멀티어댑터"],
  },
  {
    id: "rome",
    name: "로마",
    country: "이탈리아",
    flag: "🇮🇹",
    region: "유럽",
    tagline: "도시 전체가 거대한 박물관",
    lat: 41.90, lng: 12.50, c1: "#ea580c", c2: "#65a30d",
    bestSeason: "4~5월 · 9~10월",
    budgetPerDay: "€100~170",
    flightTime: "약 13시간(경유)",
    vibe: ["역사", "젤라또", "파스타"],
    mustSee: [
      { title: "콜로세움", desc: "2천년 원형경기장, 야간 입장 추천." },
      { title: "바티칸 박물관", desc: "시스티나 천장화, 새벽 예약." },
      { title: "트레비 분수", desc: "동전 던지면 다시 온다는 전설." },
    ],
    tips: ["로마패스 교통+입장", "식당 자릿세(coperto)", "물병 들고 식수대 활용"],
    gear: ["워킹화", "물병", "햇빛모자"],
  },
  {
    id: "barcelona",
    name: "바르셀로나",
    country: "스페인",
    flag: "🇪🇸",
    region: "유럽",
    tagline: "가우디의 도시, 지중해 미식",
    lat: 41.39, lng: 2.17, c1: "#f43f5e", c2: "#facc15",
    bestSeason: "5~6월 · 9월",
    budgetPerDay: "€90~160",
    flightTime: "약 14시간(경유)",
    vibe: ["건축", "타파스", "해변"],
    mustSee: [
      { title: "사그라다 파밀리아", desc: "140년째 짓는 가우디 대성당." },
      { title: "구엘 공원", desc: "모자이크 타일의 동화." },
      { title: "보케리아 시장", desc: "하몽·샹그리아·과일주스." },
    ],
    tips: ["주요 명소 시간지정 예약", "소매치기 최다 주의", "시에스타 영업시간"],
    gear: ["보안 백팩", "샌들", "선글라스"],
  },
  {
    id: "swiss",
    name: "인터라켄",
    country: "스위스",
    flag: "🇨🇭",
    region: "유럽",
    tagline: "알프스의 심장, 융프라우 베이스",
    lat: 46.68, lng: 7.85, c1: "#0ea5e9", c2: "#a3e635",
    bestSeason: "6~9월 (트레킹)",
    budgetPerDay: "CHF150~250",
    flightTime: "약 13시간(경유)",
    vibe: ["설산", "트레킹", "패러글라이딩"],
    mustSee: [
      { title: "융프라우요흐", desc: "유럽의 지붕, 톱오브유럽." },
      { title: "쉴트호른", desc: "007 회전식당 파노라마." },
      { title: "브리엔츠 호수", desc: "에메랄드빛 유람선." },
    ],
    tips: ["스위스트래블패스 검토", "날씨 변동 — 라이브캠 확인", "물가 매우 높음"],
    gear: ["등산화", "방풍 자켓", "선글라스"],
  },
  {
    id: "london",
    name: "런던",
    country: "영국",
    flag: "🇬🇧",
    region: "유럽",
    tagline: "전통과 펑크가 공존하는 도시",
    lat: 51.51, lng: -0.13, c1: "#1d4ed8", c2: "#dc2626",
    bestSeason: "5~9월",
    budgetPerDay: "£100~180",
    flightTime: "약 14시간",
    vibe: ["뮤지컬", "박물관", "펍", "마켓"],
    mustSee: [
      { title: "대영박물관", desc: "무료 입장, 로제타석." },
      { title: "웨스트엔드 뮤지컬", desc: "라이언킹·위키드." },
      { title: "버로우 마켓", desc: "런던 최고의 푸드마켓." },
    ],
    tips: ["오이스터 카드", "박물관 대부분 무료", "비 대비 필수"],
    gear: ["방수 자켓", "우산", "워킹화"],
  },
  {
    id: "newyork",
    name: "뉴욕",
    country: "미국",
    flag: "🇺🇸",
    region: "미주",
    tagline: "잠들지 않는 도시, 세계의 수도",
    lat: 40.71, lng: -74.0, c1: "#7c3aed", c2: "#f59e0b",
    bestSeason: "4~6월 · 9~11월",
    budgetPerDay: "$200~350",
    flightTime: "약 14시간",
    vibe: ["마천루", "브로드웨이", "미술관", "재즈"],
    mustSee: [
      { title: "탑오브더록", desc: "엠파이어 보이는 최고 전망." },
      { title: "센트럴파크", desc: "자전거·피크닉." },
      { title: "MoMA·메트", desc: "현대미술의 성지." },
    ],
    tips: ["시티패스로 묶음 할인", "팁 문화 18~20%", "지하철 24시간"],
    gear: ["편한 운동화", "보조배터리", "크로스백"],
  },
  {
    id: "hawaii",
    name: "하와이",
    country: "미국",
    flag: "🇺🇸",
    region: "미주",
    tagline: "알로하, 태평양의 낙원",
    lat: 21.31, lng: -157.86, c1: "#06b6d4", c2: "#fb923c",
    bestSeason: "연중 (4~5월·9~10월 한산)",
    budgetPerDay: "$180~320",
    flightTime: "약 9시간",
    vibe: ["서핑", "스노클링", "드라이브", "선셋"],
    mustSee: [
      { title: "와이키키 해변", desc: "초보 서핑 입문." },
      { title: "다이아몬드 헤드", desc: "분화구 트레킹 일출." },
      { title: "하나우마 베이", desc: "스노클링 천국(예약필수)." },
    ],
    tips: ["렌터카 필수", "리프세이프 선크림만", "ESTA 필요"],
    gear: ["스노클 세트", "방수 가방", "리프 선크림"],
  },
  {
    id: "sydney",
    name: "시드니",
    country: "호주",
    flag: "🇦🇺",
    region: "오세아니아",
    tagline: "오페라하우스와 해변의 도시",
    lat: -33.87, lng: 151.21, c1: "#0284c7", c2: "#fbbf24",
    bestSeason: "9~11월 · 3~5월",
    budgetPerDay: "AUD180~300",
    flightTime: "약 10시간",
    vibe: ["해변", "서핑", "와인", "야경"],
    mustSee: [
      { title: "오페라하우스", desc: "백스테이지 투어 가능." },
      { title: "본다이 비치", desc: "본다이~쿠지 해안 산책로." },
      { title: "블루마운틴", desc: "세자매봉 협곡 절경." },
    ],
    tips: ["오팔 카드 교통", "자외선 매우 강함", "여름엔 한국과 반대 계절"],
    gear: ["강력 선크림", "래쉬가드", "선글라스"],
  },
  {
    id: "seoul",
    name: "서울",
    country: "대한민국",
    flag: "🇰🇷",
    region: "국내",
    tagline: "궁궐과 한강, 24시 도시",
    lat: 37.57, lng: 126.98, c1: "#3b82f6", c2: "#ec4899",
    bestSeason: "4월 벚꽃 · 10월 단풍",
    budgetPerDay: "₩70,000~130,000",
    flightTime: "—",
    vibe: ["궁궐", "한강", "쇼핑", "야경"],
    mustSee: [
      { title: "경복궁 야간개장", desc: "한복 입고 입장 무료." },
      { title: "북촌·익선동", desc: "한옥 골목 카페." },
      { title: "남산서울타워", desc: "케이블카 야경." },
    ],
    tips: ["티머니 카드", "따릉이 한강 라이딩", "야시장 푸드트럭"],
    gear: ["운동화", "보조배터리", "에코백"],
  },
  {
    id: "yeosu",
    name: "여수",
    country: "대한민국",
    flag: "🇰🇷",
    region: "국내",
    tagline: "밤바다와 케이블카의 낭만",
    lat: 34.76, lng: 127.66, c1: "#0d9488", c2: "#9333ea",
    bestSeason: "봄·여름",
    budgetPerDay: "₩70,000~120,000",
    flightTime: "KTX 약 3시간",
    vibe: ["밤바다", "케이블카", "회"],
    mustSee: [
      { title: "여수 해상케이블카", desc: "바다 위를 가르는 야경." },
      { title: "돌산공원·이순신광장", desc: "노을 명소." },
      { title: "오동도", desc: "동백 산책로." },
    ],
    tips: ["밤바다 버스킹 거리", "돌게장·갓김치", "성수기 숙박 급등"],
    gear: ["가디건", "운동화", "카메라"],
  },
  {
    id: "singapore",
    name: "싱가포르",
    country: "싱가포르",
    flag: "🇸🇬",
    region: "아시아",
    tagline: "정원 속 미래도시",
    lat: 1.35, lng: 103.82, c1: "#dc2626", c2: "#0ea5e9",
    bestSeason: "연중 (2~4월 강수 적음)",
    budgetPerDay: "$120~200",
    flightTime: "약 6시간 30분",
    vibe: ["마리나베이", "미식", "테마파크"],
    mustSee: [
      { title: "가든스 바이 더 베이", desc: "슈퍼트리 라이트쇼." },
      { title: "마리나베이샌즈", desc: "인피니티 풀 야경." },
      { title: "센토사·유니버설", desc: "가족 테마파크." },
    ],
    tips: ["MRT 깨끗·편리", "껌 반입 금지 등 규정", "호커센터 미식"],
    gear: ["얇은 옷", "우산", "보조배터리"],
  },
  {
    id: "cebu",
    name: "세부",
    country: "필리핀",
    flag: "🇵🇭",
    region: "아시아",
    tagline: "고래상어와 캐녀닝의 섬",
    lat: 10.32, lng: 123.89, c1: "#0891b2", c2: "#f59e0b",
    bestSeason: "12~5월 (건기)",
    budgetPerDay: "$40~80",
    flightTime: "약 4시간 30분",
    vibe: ["다이빙", "캐녀닝", "리조트"],
    mustSee: [
      { title: "오슬롭 고래상어", desc: "세계적 스노클링 포인트." },
      { title: "카와산 폭포 캐녀닝", desc: "절벽 다이빙 액티비티." },
      { title: "보홀 초콜릿힐", desc: "안경원숭이 투어." },
    ],
    tips: ["보홀과 묶어 일정", "현지 투어 흥정", "방수장비 필수"],
    gear: ["아쿠아슈즈", "방수 액션캠", "구급약"],
  },
  {
    id: "kyoto",
    name: "교토",
    country: "일본",
    flag: "🇯🇵",
    region: "아시아",
    tagline: "천 년 고도, 사찰과 게이샤",
    lat: 35.01, lng: 135.77, c1: "#b91c1c", c2: "#16a34a",
    bestSeason: "3월말 벚꽃 · 11월 단풍",
    budgetPerDay: "¥10,000~18,000",
    flightTime: "오사카 경유 약 2시간",
    vibe: ["사찰", "단풍", "기모노", "전통"],
    mustSee: [
      { title: "후시미이나리", desc: "끝없는 붉은 토리이 터널." },
      { title: "아라시야마 대나무숲", desc: "이른 아침이 한산." },
      { title: "기요미즈데라", desc: "단풍 명소, 야간 라이트업." },
    ],
    tips: ["버스 1일권", "성수기 새벽 일정", "기모노 렌탈 산책"],
    gear: ["편한 신발", "양산", "에코백"],
  },
  {
    id: "vienna",
    name: "비엔나",
    country: "오스트리아",
    flag: "🇦🇹",
    region: "유럽",
    tagline: "음악과 카페의 황실 도시",
    lat: 48.21, lng: 16.37, c1: "#7c3aed", c2: "#f59e0b",
    bestSeason: "4~5월 · 9~10월",
    budgetPerDay: "€100~160",
    flightTime: "약 13시간(경유)",
    vibe: ["클래식", "카페", "궁전"],
    mustSee: [
      { title: "쇤브룬 궁전", desc: "합스부르크 여름궁전과 정원." },
      { title: "국립오페라극장", desc: "입석 저렴 관람." },
      { title: "자허 카페", desc: "원조 자허토르테." },
    ],
    tips: ["빈 시티카드", "콘서트 사전 예약", "분수대 식수 가능"],
    gear: ["단정한 옷(공연)", "워킹화", "어댑터"],
  },
  {
    id: "queenstown",
    name: "퀸스타운",
    country: "뉴질랜드",
    flag: "🇳🇿",
    region: "오세아니아",
    tagline: "남반구의 액티비티 수도",
    lat: -45.03, lng: 168.66, c1: "#0d9488", c2: "#f43f5e",
    bestSeason: "12~2월(여름) · 6~8월(스키)",
    budgetPerDay: "NZD180~300",
    flightTime: "약 12시간(경유)",
    vibe: ["번지점프", "스키", "트레킹", "와인"],
    mustSee: [
      { title: "번지점프 발원지", desc: "카와라우 다리 세계 최초." },
      { title: "밀포드 사운드", desc: "피오르드 크루즈 절경." },
      { title: "스카이라인 곤돌라", desc: "루지와 파노라마." },
    ],
    tips: ["렌터카로 자유여행", "액티비티 묶음 할인", "일교차 대비"],
    gear: ["방풍 자켓", "등산화", "선글라스"],
  },
];

export const REGIONS: Region[] = ["국내", "아시아", "유럽", "미주", "오세아니아"];

export function getDestination(id: string) {
  return DESTINATIONS.find((d) => d.id === id);
}
